/**
 * Vendors the two webfonts into `public/fonts/` and writes the @font-face CSS.
 *
 * The site otherwise makes no third-party requests at all, and a Google Fonts
 * <link> would hand every visitor's IP address to Google — which a German court
 * ruled a GDPR violation in 2022 (LG München I, 3 O 17493/20). Self-hosting
 * keeps the promise the front page makes: nothing leaves the browser.
 *
 * Three slices are taken per face: `latin` for thorn, eth and ash, `latin-ext`
 * for the IPA letters and modifier marks, and a `marks` subset cut to an exact
 * string for the handful of Greek letters, combining marks and subscripts that
 * neither covers. Run with:
 *
 *     node scripts/fetch-fonts.mjs
 */

import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const OUT_DIR = resolve(ROOT, 'public/fonts')

// A modern desktop UA is required, or the API serves legacy ttf instead of woff2.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

const FAMILIES = [
  { css: 'Cardo:ital,wght@0,400;0,700;1,400', slug: 'cardo' },
  { css: 'Grenze+Gotisch:wght@400', slug: 'grenze-gotisch' },
]

/** The two subsets we keep, identified by a codepoint only that subset covers. */
const WANTED = [
  { name: 'latin-ext', probe: 'U+0100-02BA' },
  { name: 'latin', probe: 'U+0000-00FF' },
]

/*
 * Characters this app puts on screen that neither latin subset carries. Without
 * these the browser silently substitutes a system font mid-word, which is how
 * the acute in a PIE form ended up floating beside its vowel instead of over
 * it — a different typeface was drawing it.
 *
 *   ́  ̥   combining acute and ring-below: PIE stress, and syllabic r̥ l̥ n̥
 *   β θ χ   IPA, and the Proto-Italic fricatives
 *   ο ς     genuine Greek, cited in the notes for the *-os ending
 *   ₁ ₂ ₃   laryngeal subscripts, which is how h₁ h₂ h₃ are written
 *   → ⟨ ⟩   the arrow and the angle brackets that mark a grapheme
 *
 * `tests/fonts.test.ts` fails if the engine can render anything not covered
 * here, so this list cannot quietly fall behind the sound laws.
 */
const SUPPLEMENT = '̥́βθοςχ₁₂₃→⟨⟩'

/** Split a Google Fonts stylesheet into its @font-face blocks. */
function parseFaces(css) {
  return [...css.matchAll(/@font-face\s*\{([^}]*)\}/g)].map(([, body]) => {
    const field = (name) => body.match(new RegExp(`${name}:\\s*([^;]+)`))?.[1]?.trim()
    return {
      style: field('font-style') ?? 'normal',
      weight: field('font-weight') ?? '400',
      range: field('unicode-range') ?? '',
      url: body.match(/url\((https:[^)]+)\)/)?.[1],
    }
  })
}

const faces = []

for (const family of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${family.css}&display=swap`
  const css = await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => r.text())

  for (const face of parseFaces(css)) {
    const subset = WANTED.find((w) => face.range.startsWith(w.probe))
    if (!subset || !face.url) continue

    const file = `${family.slug}-${face.weight}-${face.style}-${subset.name}.woff2`
    const bytes = Buffer.from(await fetch(face.url).then((r) => r.arrayBuffer()))
    await mkdir(OUT_DIR, { recursive: true })
    await writeFile(resolve(OUT_DIR, file), bytes)

    faces.push({ ...face, file, family: family.slug, kb: Math.round(bytes.length / 1024) })
    console.log(`${file.padEnd(46)} ${String(Math.round(bytes.length / 1024)).padStart(4)} kB`)
  }

  /*
   * Google will cut a subset to an exact string, which is the only way to get
   * these: they are scattered across the Greek, Greek-Extended and punctuation
   * subsets, and pulling all three whole would cost far more than the few
   * hundred bytes the glyphs actually take.
   */
  const supUrl =
    `https://fonts.googleapis.com/css2?family=${family.css}` +
    `&text=${encodeURIComponent(SUPPLEMENT)}&display=swap`
  const supCss = await fetch(supUrl, { headers: { 'User-Agent': UA } }).then((r) => r.text())

  for (const face of parseFaces(supCss)) {
    if (!face.url) continue
    const file = `${family.slug}-${face.weight}-${face.style}-marks.woff2`
    const bytes = Buffer.from(await fetch(face.url).then((r) => r.arrayBuffer()))
    await writeFile(resolve(OUT_DIR, file), bytes)
    faces.push({ ...face, file, family: family.slug })
    console.log(`${file.padEnd(46)} ${String(Math.round(bytes.length / 1024)).padStart(4)} kB`)
  }
}

const NAME = { cardo: 'Cardo', 'grenze-gotisch': 'Grenze Gotisch' }

const banner = `/*
 * Self-hosted webfaces. Generated by scripts/fetch-fonts.mjs — do not edit.
 *
 * Vendored rather than linked so the page makes no third-party request. Three
 * slices per face: latin, latin-ext for the IPA letters the transcriptions are
 * set in, and a small marks subset for the Greek letters, combining marks and
 * laryngeal subscripts that neither of those carries.
 */
`

const css =
  banner +
  faces
    .map(
      (f) => `
@font-face {
  font-family: '${NAME[f.family]}';
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: swap;
  src: url('/fonts/${f.file}') format('woff2');
  unicode-range: ${f.range};
}`,
    )
    .join('\n')

await writeFile(resolve(ROOT, 'src/fonts.css'), css.trimStart() + '\n')
console.log(`\nWrote src/fonts.css with ${faces.length} faces.`)
